### ISSUE TITLE
[ExpandCollapse] Custom styling of PanelWrapper button

### ISSUE THREAD

**Issue by ah-arch** [telus/tds-core#656] opened 2018-06-19 18:36 UTC
## Description

* Some scenarios require more variety of objects to be displayed in the toggle button of an ExpandCollapse Panel, but currently only [strings](https://github.com/telus/tds-core/blob/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx#L166-L168
) are allowed for:
  * panelHeader
  * panelSubtext
  * panelTertiaryText

## Discussion

* Could allow flexibility with `PropTypes.oneOfType([PropTypes.string, PropTypes.node])`, but may conflict with the original `Text` wrappers
* Seems like the styling wrappers needs to account for this new scenario:
  * [panelHeader](https://github.com/telus/tds-core/blob/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx#L88): `<Text size="large">{header}</Text>`
  * [panelSubtext](https://github.com/telus/tds-core/blob/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx#L90): `<Text size="small">{subtext}</Text>`
  * [panelTertiaryText](https://github.com/telus/tds-core/blob/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx#L93-L107): `<Text size="large/medium">{tertiaryText}</Text>`

## Designs

<img width="400" alt="expandcollapse - need extra prop type" src="https://user-images.githubusercontent.com/4450690/41616680-8bce996e-73cc-11e8-8053-cff609dee367.png">

* Where the desired props are:
   * header = `<Box between={1} inline><img /><Heading level="2" /></Box>` + `styles.headerAlign`
   * subtext = `<Box between={1}><Text size="medium" /><Text size="medium" /></Box>`
   * tertiaryText = `<DecorativeIcon />`

## Meta

* TDS version: [v1.0.3](https://github.com/telus/tds-core/tree/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse)
* Willing to develop solution: Yes
* Has workaround: No
* High impact: Yes

**Comment by theetrain** [comment] 2018-06-20 18:36
Thanks for the suggestion, Ally.

@lucylist @Berjesty - Please review the design viability for this feature and then we'll move forward with a recommendation.

**Comment by ah-arch** [comment] 2018-06-27 14:40
On an unrelated prop issue, our project had to bypass `children: childrenOfType(Panel).isRequired` of [Panels](https://github.com/telus/tds-core/blob/eb94102d4ef13188218c2f36c0dfe78228c27b9d/packages/ExpandCollapse/Panels.jsx#L46).

The project's situation:
- There is a main `ExpandCollapse / Accordion` that contains a contentful list of `Block`s rendered by a `BlockTemplator`. Each `Block` component returns a `Panel`.
    - This is where the prop error occurs
- These `Block`s have to be separate components as they 1) are unique and 2) call different APIs in order to render its content and the `Panel`'s _header / subtext / tertiaryText_
    - All these unrelated API requests should not be placed at the top level where the main `ExpandCollapse / Accordion`.
    - Therefore the `Panel` should be nested in the `Block` where its headers can be manipulated

As a result, we now have a version of [Accordion](https://github.com/telus/my-account-overview/tree/master/ui/src/components/Common/Accordion) that allows nesting of Components returning Panels and also fixes all the prop warnings above. So the original issue is no longer high impact or needs an urgent fix.

**Comment by marcod1419** [comment] 2018-06-27 17:41
@ah-arch Thanks for the added info! Would you be able to split that stuff into a separate issue?

**Comment by Berjesty** [comment] 2018-07-31 20:55
Update: We have design leads this Friday, will review with them and provide feedback after.

**Comment by Berjesty** [comment] 2018-08-03 19:28
This was discussed in this week's design leads meeting and decision was made that to put this ticket on hold until all user testing for this is completed.

**Comment by theetrain** [comment] 2018-08-29 19:07
Hi @Berjesty, any updates?

**Comment by apurvray** [comment] 2018-09-12 15:34
Here is the sketch file to the custom expand collapse used in the overview page. 

We shared the designs with the myTelus tribe, Lucy, Gary Chow, Neal, and Berjesty. Berjesty also shared the designs in the Design Lead meeting a couple of times. 

Designs have gone through user testing as well and are live on the overview page (expand collapse is only used in mobile)




[Overview Expand-Collapse.zip](https://github.com/telus/tds-core/files/2375860/Overview.Expand-Collapse.zip)

**Comment by varunj90** [comment] 2018-09-19 17:30
hey @ah-arch , the approved design for this is the one that @apurvray posted above. please confirm

once you do we can move this to community backlog :)

**Comment by ah-arch** [comment] 2018-09-19 17:35
Unable to see it as I do not have sketch.
The screenshot I attached is the one deployed in our project. Are they different?

**Comment by varunj90** [comment] 2018-09-19 17:38
@apurvray please show @ah-arch the design.

@lucylist confirmed the ones @apurvray posted are good, not the screenshot.
![screen shot 2018-09-19 at 1 38 33 pm](https://user-images.githubusercontent.com/3495961/45770777-54532080-bc11-11e8-8d50-2a94c666b7e3.png)

**Comment by ah-arch** [comment] 2018-09-19 17:41
It is the same. The blue shadow is a chrome browser focus on the panel button.

**Comment by varunj90** [comment] 2018-09-19 17:42
the difference is two error messages stacked together vs separate (bill overdue, usage overages)

**Comment by ah-arch** [comment] 2018-09-19 17:46
The component accepts a list of error messages that will be stacked below if there is more than 1.
Should it should _enforce_ only 1 notification message?

**Comment by varunj90** [comment] 2018-09-19 17:55
both @lucylist and @gkychow have discussed this previously and prefer we don't stack those messages.

having it combined is better. 

an even better design can be worked upon

cc: @apurvray

**Comment by ah-arch** [comment] 2018-09-19 18:17
So the list of capitalized error messages should be joined with commas?

**Comment by varunj90** [comment] 2018-09-19 19:36
this has been discussed with @ah-arch and @apurvray offline and their team will be updating their design in the next milestone.

moving this to community backlog so @ah-arch can work on it once she has the bandwidth.

**Comment by theetrain** [comment] 2018-10-10 17:17
This discussion has been logged for the core team to review: https://telusdigital.atlassian.net/browse/TDS-975

**Comment by marcod1419** [comment] 2018-10-25 14:40
Since this is now being discussed in [tds-community](https://github.com/telus/tds-community/issues/111), I'll close this issue.

**Closed by marcod1419** 2018-10-25 14:40 UTC
Labels: priority: medium, status: design review :art:, type: enhancement
