### ISSUE TITLE
[Bug][iOS 10]["@tds/core-button": "^1.1.1"] Button text not centered

### ISSUE THREAD

**Issue by brastrullo** [telus/tds-core#794] opened 2018-11-07 16:01 UTC
## Description

- Visual bug on a button on iOS 10 Safari. On mobile the button text is not centered. From testing it’s not showing up on the latest iOS. 

## Reproduction Steps
- On telus.com navigate to Support on mobile using iOS 10 Safari
- Scroll down a few lines and click on the chat widget
- Click on Mobility and select Billing or My TELUS
- Scroll down to the primary button Start Chat
- Button text is seen aligned to the left

## Meta

- TDS version: v1.1.1
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: No

## Screenshots

<img width="1440" alt="left aligned button text screenshot" src="https://user-images.githubusercontent.com/11504992/48143247-626e0680-e27c-11e8-917a-cbbfa9976b2d.png">

- Include any relevant screenshots

**Comment by theetrain** [comment] 2018-11-07 18:12
Thanks for the report! If you have cycles to contribute a solution, we welcome it!

**Comment by saydex** [comment] 2019-05-07 22:04
Hi @theetrain, thanks for responding to the support thread. Our HS Config team is using the core-button component on the repo `sh-shs-wizard` and found out the issue is that older devices does not know how to interpret the `display: inline-flex` property.

Updating this to `display: block;` will help solve the text alignment issue.

Our pages is scheduled to be live end of May and wonder if the TDS team can give us an estimate on when the fix will be shipped? I know many components needs to be migrated to V3 and hence bug fix might have to come after June/July?

**Comment by marcod1419** [comment] 2019-05-14 14:36
This has been addressed in `core-button @2.0.7`. Thanks for the contribution, @saydex!

**Closed by marcod1419** 2019-05-14 14:36 UTC
Labels: priority: medium, status: reviewed, type: defect :bug:
