### ISSUE TITLE
Spinner is not working on real mobile devices

### ISSUE THREAD

**Issue by ivaylogabrovsky** [telus/tds-core#665] opened 2018-06-25 19:13 UTC
## Description

Spinner is not working on real mobile devices

## Reproduction Steps

Test Spinner on real mobile device

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: @tds/core-spinner v2.0.1

**Comment by marcod1419** [comment] 2018-06-26 17:16
Hi @ivaylogabrovsky! Thanks for reporting the issue. Would you be able to post some sample code that reproduces this issue? Screenshots would also be very helpful.

Thanks! :)

**Comment by ivaylogabrovsky** [comment] 2018-06-27 18:12
Here is a screen print form mobile device.

![missing spinner on login button while loading](https://user-images.githubusercontent.com/30123542/41991592-f2c5672c-7a13-11e8-8af1-f0bd11a2466d.png)

**Comment by ivaylogabrovsky** [comment] 2018-06-27 18:13
`<div className="small-view">
          <Spinner spinning={submited} >
            <Button onClick={() => { return onSubmit() }} data-id="login" type="submit">
              {textContent && textContent.loginBtnLabel && textContent.loginBtnLabel}
            </Button
            >
          </Spinner>
        </div>`

`.small-view {
  @include mq($until: md) {
    display: block;
  }
  @include mq($from: md) {
    display: none;
  }
}`

**Comment by marcod1419** [comment] 2018-07-04 15:20
Ran some tests and found that the issue does not actually lie in the `spinner` component. The issue seems to be with the variable, `submited` assigned to the `spinning` prop. Hardcoding the prop to be `true` allows the spinner to [show up on mobile normally](https://i.imgur.com/DFPQ0fP.png). I noticed that the variable assigned to the `spinning` prop, `submited` is spelled incorrectly, so it may be worth looking into this being a typo.

**Closed by marcod1419** 2018-07-04 15:20 UTC
Labels: priority: high, status: review needed, type: defect
